% Compute power spectrum

% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 03-Apr-2025 13:51:47
load ECG_1.mat
ECG1 = ECG(1, :);
% Parameters
timeLimits = [0 480]; % seconds
frequencyLimits = [0 100]; % Hz

%%
% Index into signal time region of interest
ECG1_ROI = ECG1(:);
sampleRate = 200; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(ECG1_ROI)-1))+1;
ECG1_ROI = ECG1_ROI(minIdx:maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[PECG1_ROI, FECG1_ROI] = pspectrum(ECG1_ROI,sampleRate, ...
    'FrequencyLimits',frequencyLimits);
